name: Build latest PDF

on:
  push:
    branches:
      # PRs can only use caches from their target branch. We therefore need to
      # make sure we run on 'main' too.
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  style:
    name: Build latest PDF
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: tex/FormalLanguageConstrainedReachabilityLectureNotes.tex
          work_in_root_file_dir: true
          latexmk_use_lualatex: true
          extra_system_packages: "font-liberation"
          latexmk_shell_escape: true

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: FormalLanguageConstrainedReachabilityLectureNotes_latest
          path: tex/FormalLanguageConstrainedReachabilityLectureNotes.pdf
